name: amazon_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  file_picker: ^8.0.0+1
  cloudinary: ^1.2.0
  flutter_rating_bar: ^4.0.1
  pay: ^2.0.0
  intl: ^0.18.0
  d_chart: ^2.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/gpay.json
